steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'GOOGLE_SHEETS_API_KEY=${_GOOGLE_SHEETS_API_KEY}',
        '--build-arg',
        'GOOGLE_SHEETS_ID=${_GOOGLE_SHEETS_ID}',
        '--build-arg',
        'GOOGLE_SHEETS_TAB_NAME=${_GOOGLE_SHEETS_TAB_NAME}',
        '-t',
        'gcr.io/$PROJECT_ID/f3-region-pages',
        '.',
      ]
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/f3-region-pages']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'f3-region-pages'
      - '--image=gcr.io/$PROJECT_ID/f3-region-pages'
      - '--platform=managed'
      - '--region=${_REGION}'
      - '--allow-unauthenticated'
      - '--set-env-vars=GOOGLE_SHEETS_API_KEY=${_GOOGLE_SHEETS_API_KEY},GOOGLE_SHEETS_ID=${_GOOGLE_SHEETS_ID},GOOGLE_SHEETS_TAB_NAME=${_GOOGLE_SHEETS_TAB_NAME}'
      - '--set-env-vars=POSTGRES_URL=${_POSTGRES_URL}'
images:
  - 'gcr.io/$PROJECT_ID/f3-region-pages'
